# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Send requests

on:
  schedule:
    # On the 9th of the month at 4pm UTC = 9am PST
    # https://crontab.guru/#0_16_9_*_*
    - cron: "0 16 9 * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run script
        run: |
          python init.py
        env:
          VENMO_ACCESS_TOKEN: ${{ secrets.VENMO_ACCESS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          I_FRIEND_ID: ${{ secrets.I_FRIEND_ID }}
          J_FRIEND_ID: ${{ secrets.J_FRIEND_ID }}
          K_FRIEND_ID: ${{ secrets.K_FRIEND_ID }}
          L_FRIEND_ID: ${{ secrets.L_FRIEND_ID }}
          S_FRIEND_ID: ${{ secrets.S_FRIEND_ID }}
          Y_FRIEND_ID: ${{ secrets.Y_FRIEND_ID }}
          P_FRIEND_ID: ${{ secrets.P_FRIEND_ID }}
