name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  actions: write
jobs:
  workflow-keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
